services:
  patrik-warranty-form:
    image: time4action/patrik-warranty-form:latest
    container_name: patrik-warranty-form
    restart: unless-stopped
    ports:
      - "4000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
